### ISSUE TITLE
Memory Monitoring Should be Handled Differently for Each OS

### ISSUE THREAD

**Issue by agomez08** [ni/niveristand-system-monitor-custom-device#11]
See this article:
https://knowledge.ni.com/KnowledgeArticleDetails?id=kA00Z000000P9usSAC&l=en-US

The CD is coded to provide 3 output channels for memory: Total Memory, Available and Largest Free. 

FreePhysMem won't be accurate for Linux RT. Since LargestMem would throw an error, it is being filter to only run on Pharlap, which means it will always throw zero for Linux RT.

The CD could be coded to do the next instead:

- Check OS from System Explorer code. 

- Keep current channels for Pharlap.

- For Linux RT, generate the channels Total Memory and LVRT Mem Usage.

- For Engine code, keep code as it is for Pharlap.

- For Engine code, use System Exec call as recommended on the KB to check LVRT process memory usage.

**Comment by rtzoeller** [comment]
Thanks for reporting this @agomez08!

Unfortunately we aren't actively maintaining this custom device - it was created as a demo by a former team member and there are no current plans to update it. There are obviously some other issues with the custom device as well, such as the CHMs being the default boilerplate.

If you want to make the changes, I would be happy to review and merge them.

---

There are some technical challenges around the idea of per-target type channels which I'll document here for posterity.

Currently there is no Action VI for handling "target type changed" events - you can create the custom device based on the currently active OS, but there is no direct way to be notified when the target type changes.

You could likely use an "on save" action VI to watch for target type/OS updates - you'd also likely want to add logic to the individual pages to force a refresh if the system definition has not yet been saved since the OS was updated.

It is also possible to change the target type outside of the System Explorer, either using the .NET API or (in new versions) through the right rail of the channel mapping diagram. These would not trigger any of the Action VIs mentioned earlier, and you would likely want to fail the compile/deployment to force the user to update the custom device.

**Comment by Karl-G1** [comment]
This has effectively been addressed by #28. It removed the unsupported `FreePhysMem` channel now that the CD only supports Linux targets.

Any desire to add more channel monitoring is not planned for this CD as far as NI R&D is concerned, but this is open source and well-tested contributions are welcome!
