### ISSUE TITLE
Does Not Deploy with FPGA Add-On

### ISSUE THREAD

**Issue by christinesparks** [ni/niveristand-system-monitor-custom-device#16]
I can deploy the System Monitor 2020 custom device by itself in VS 2020. I can deploy the FPGA Add-On custom device by itself in VS 2020. But I can't deploy the two together. The last one added into the project errors saying the VI is broken and check the run arrow. I'm guessing this is due to mismatched custom device tool dependencies or some other shared dependency, but I couldn't find documentation recommending which versions they were built against to know which one I should rebuild.

Let me know if you need more info!

**Comment by christinesparks** [comment]
FYI @rtzoeller - working on this as part of a larger system integration test effort

**Comment by buckd** [comment]
It's most likely the Inline Async API. Any change to the API can potentially cause this kind of thing because when those VIs are pulled into LLBs, there is no namespacing or uniquifying rename. For some custom devices, we have fixed this, but likely not this one, since we haven't made any real code changes since the first release.

**Comment by buckd** [comment]
To work around this, you can rename the items from the Inline Async API when they are pulled into the engine LLB. See what we did for the [SLSC EDS custom device](https://github.com/ni/niveristand-slsc-eds-custom-device/pull/51).

**Comment by buckd** [comment]
VeriStand Custom Device Wizard [Issue 29](https://github.com/ni/niveristand-custom-device-wizard/issues/29).
